import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";


export const metadata: Metadata = {
  title: "Mercadoliebre",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="h-16 bg-yellow-300 flex">
          <form action="/items" className="px-4 flex m-auto gap-4 max-w-screen-lg flex-1">
            <Link href={"/"} className="text-black-500 text-lg items-center">LibreMercado</Link>
            <input type="text" name="search" className="h-8 px-2 flex-1" />
            <button type="submit" className="bg-gray-300 px-4 py-1 h-8 text-slate-800">Buscar</button>
          </form>
        </header>
        <main className="max-w-screen-xl px-4 m-auto gap-4">{children}</main>
      </body>
    </html>
  );
}
